# Generated by Django 2.2.15 on 2021-10-15 09:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('task_id', models.CharField(max_length=14, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(8)])),
                ('task_name', models.TextField(blank=True, null=True)),
                ('client', models.CharField(blank=True, max_length=40, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('With client', 'With Client'), ('blocked', 'BLOCKED'), ('complete', 'COMPLETE')], default='active', max_length=40)),
                ('owner', models.CharField(blank=True, max_length=40, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tasks',
                'ordering': ['-task_id'],
            },
        ),
        migrations.CreateModel(
            name='AccountTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('user_status', models.CharField(choices=[('active', 'Active'), ('With client', 'With Client'), ('blocked', 'BLOCKED'), ('complete', 'COMPLETE')], default='active', max_length=40)),
                ('user_blocked', models.BooleanField(default=False)),
                ('time', models.TimeField(default='20:00')),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Tasks')),
            ],
            options={
                'verbose_name_plural': 'AccountTasks',
                'ordering': ['-task_id'],
            },
        ),
    ]
