# Generated by Django 2.2.15 on 2021-10-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.TextField(blank=True, null=True)),
                ('client', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True)),
                ('end_date', models.DateTimeField(blank=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('owner', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-task_id'],
            },
        ),
    ]
