# Generated by Django 2.2.15 on 2021-10-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttask',
            name='time',
            field=models.TimeField(default='01:00'),
        ),
    ]
