# Generated by Django 2.2.15 on 2021-10-12 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['-task_id'], 'verbose_name_plural': 'Tasks'},
        ),
    ]
