# Generated by Django 2.2.15 on 2021-10-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20211012_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='client',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='owner',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('With client', 'With Client'), ('blocked', 'BLOCKED')], default='active', max_length=40),
        ),
    ]
