# Generated by Django 2.2.15 on 2021-10-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20211012_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
