# Generated by Django 2.2.15 on 2021-10-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20211013_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttask',
            name='user_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accounttask',
            name='user_status',
            field=models.CharField(choices=[('active', 'Active'), ('With client', 'With Client'), ('blocked', 'BLOCKED'), ('complete', 'COMPLETE')], default='active', max_length=40),
        ),
    ]
