# Generated by Django 2.2.15 on 2021-10-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20211013_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
