# Generated by Django 2.2.15 on 2021-10-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20211014_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttask',
            name='time',
            field=models.TimeField(default='20:00'),
        ),
    ]
